name: hd
description: custom get CLI,(for flutter project with getx)
version: 1.0.5
repository: https://github.com/helloDolin

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  path: ^1.8.0

executables:
  hd: hd # 表示将 bin/hd.dart 的内容作为 hd 命令行工具的入口

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
